DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS messages;

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    login VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    user_id BIGINT,
    text VARCHAR,
    created_at TIMESTAMP DEFAULT NOW()
);